# Generated by Django 5.1.3 on 2024-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bissextile', '0002_alter_bissextile_endpoint_utilise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bissextile',
            name='annee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bissextile',
            name='annee_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bissextile',
            name='annee_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
