# Generated by Django 5.1.3 on 2024-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bissextile', '0003_alter_bissextile_annee_alter_bissextile_annee_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bissextile',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
